
INSERT INTO `Kab._kota` (`name`, `province_id`) VALUES
('Kab. Aceh Barat', 1),
('Kab. Aceh Barat Daya', 1),
('Kab. Aceh Besar', 1),
('Kab. Aceh Jaya', 1),
('Kab. Aceh Selatan', 1),
('Kab. Aceh Singkil', 1),
('Kab. Aceh Tamiang', 1),
('Kab. Aceh Tengah', 1),
('Kab. Aceh Tenggara', 1),
('Kab. Aceh Timur', 1),
('Kab. Aceh Utara', 1),
('Kab. Bener Meriah', 1),
('Kab. Bireuen', 1),
('Kab. Gayo Lues', 1),
('Kab. Nagan Raya', 1),
('Kab. Pidie', 1),
('Kab. Pidie Jaya', 1),
('Kab. Simeulue', 1),
('Kota Banda Aceh', 1),
('Kota Langsa', 1),
('Kota Lhokseumawe', 1),
('Kota Sabang', 1),
('Kota Subulussalam', 1),
('Kab. Badung', 2),
('Kab. Bangli', 2),
('Kab. Buleleng', 2),
('Kab. Gianyar', 2),
('Kab. Jembrana', 2),
('Kab. Karangasem', 2),
('Kab. Klungkung', 2),
('Kab. Tabanan', 2),
('Kota Denpasar', 2),
('Kab. Bangka', 3),
('Kab. Bangka Barat', 3),
('Kab. Bangka Selatan', 3),
('Kab. Bangka Tengah', 3),
('Kab. Belitung', 3),
('Kab. Belitung Timur', 3),
('Kota Pangkal Pinang', 3),
('Kab. Lebak', 4),
('Kab. Pandeglang', 4),
('Kab. Serang', 4),
('Kab. Tangerang', 4),
('Kota Cilegon', 4),
('Kota Serang', 4),
('Kota Tangerang', 4),
('Kota Tangerang Selatan', 4),
('Kab. Bengkulu Selatan', 5),
('Kab. Bengkulu Tengah', 5),
('Kab. Bengkulu Utara', 5),
('Kab. Kaur', 5),
('Kab. Kepahiang', 5),
('Kab. Lebong', 5),
('Kab. Muko Muko', 5),
('Kab. Rejang Lebong', 5),
('Kab. Seluma', 5),
('Kota Bengkulu', 5),
('Kab. Bantul', 6),
('Kab. Gunung Kidul', 6),
('Kab. Kulon Progo', 6),
('Kab. Sleman', 6),
('Kota Yogyakarta', 6),
('Kab. Adm. Kepulauan Seribu', 7),
('Kota Adm. Jakarta Barat', 7),
('Kota Adm. Jakarta Pusat', 7),
('Kota Adm. Jakarta Selatan', 7),
('Kota Adm. Jakarta Timur', 7),
('Kota Adm. Jakarta Utara', 7),
('Kab. Boalemo', 8),
('Kab. Bone Bolango', 8),
('Kab. Gorontalo', 8),
('Kab. Gorontalo Utara', 8),
('Kab. Pohuwato', 8),
('Kota Gorontalo', 8),
('Kab. Batanghari', 9),
('Kab. Bungo', 9),
('Kab. Kerinci', 9),
('Kab. Merangin', 9),
('Kab. Muaro Jambi', 9),
('Kab. Sarolangun', 9),
('Kab. Tanjung Jabung Barat', 9),
('Kab. Tanjung Jabung Timur', 9),
('Kab. Tebo', 9),
('Kota Jambi', 9),
('Kota Sungai Penuh', 9),
('Kab. Bandung', 10),
('Kab. Bandung Barat', 10),
('Kab. Bekasi', 10),
('Kab. Bogor', 10),
('Kab. Ciamis', 10),
('Kab. Cianjur', 10),
('Kab. Cirebon', 10),
('Kab. Garut', 10),
('Kab. Indramayu', 10),
('Kab. Karawang', 10),
('Kab. Kuningan', 10),
('Kab. Majalengka', 10),
('Kab. Pangandaran', 10),
('Kab. Purwakarta', 10),
('Kab. Subang', 10),
('Kab. Sukabumi', 10),
('Kab. Sumedang', 10),
('Kab. Tasikmalaya', 10),
('Kota Bandung', 10),
('Kota Banjar', 10),
('Kota Bekasi', 10),
('Kota Bogor', 10),
('Kota Cimahi', 10),
('Kota Cirebon', 10),
('Kota Depok', 10),
('Kota Sukabumi', 10),
('Kota Tasikmalaya', 10),
('Kab. Banjarnegara', 11),
('Kab. Banyumas', 11),
('Kab. Batang', 11),
('Kab. Blora', 11),
('Kab. Boyolali', 11),
('Kab. Brebes', 11),
('Kab. Cilacap', 11),
('Kab. Demak', 11),
('Kab. Grobogan', 11),
('Kab. Jepara', 11),
('Kab. Karanganyar', 11),
('Kab. Kebumen', 11),
('Kab. Kendal', 11),
('Kab. Klaten', 11),
('Kab. Kudus', 11),
('Kab. Magelang', 11),
('Kab. Pati', 11),
('Kab. Pekalongan', 11),
('Kab. Pemalang', 11),
('Kab. Purbalingga', 11),
('Kab. Purworejo', 11),
('Kab. Rembang', 11),
('Kab. Semarang', 11),
('Kab. Sragen', 11),
('Kab. Sukoharjo', 11),
('Kab. Tegal', 11),
('Kab. Temanggung', 11),
('Kab. Wonogiri', 11),
('Kab. Wonosobo', 11),
('Kota Magelang', 11),
('Kota Pekalongan', 11),
('Kota Salatiga', 11),
('Kota Semarang', 11),
('Kota Surakarta', 11),
('Kota Tegal', 11),
('Kab. Bangkalan', 12),
('Kab. Banyuwangi', 12),
('Kab. Blitar', 12),
('Kab. Bojonegoro', 12),
('Kab. Bondowoso', 12),
('Kab. Gresik', 12),
('Kab. Jember', 12),
('Kab. Jombang', 12),
('Kab. Kediri', 12),
('Kab. Lamongan', 12),
('Kab. Lumajang', 12),
('Kab. Madiun', 12),
('Kab. Magetan', 12),
('Kab. Malang', 12),
('Kab. Mojokerto', 12),
('Kab. Nganjuk', 12),
('Kab. Ngawi', 12),
('Kab. Pacitan', 12),
('Kab. Pamekasan', 12),
('Kab. Pasuruan', 12),
('Kab. Ponorogo', 12),
('Kab. Probolinggo', 12),
('Kab. Sampang', 12),
('Kab. Sidoarjo', 12),
('Kab. Situbondo', 12),
('Kab. Sumenep', 12),
('Kab. Trenggalek', 12),
('Kab. Tuban', 12),
('Kab. Tulungagung', 12),
('Kota Batu', 12),
('Kota Blitar', 12),
('Kota Kediri', 12),
('Kota Madiun', 12),
('Kota Malang', 12),
('Kota Mojokerto', 12),
('Kota Pasuruan', 12),
('Kota Probolinggo', 12),
('Kota Surabaya', 12),
('Kab. Bengkayang', 13),
('Kab. Kapuas Hulu', 13),
('Kab. Kayong Utara', 13),
('Kab. Ketapang', 13),
('Kab. Kubu Raya', 13),
('Kab. Landak', 13),
('Kab. Melawi', 13),
('Kab. Mempawah', 13),
('Kab. Sambas', 13),
('Kab. Sanggau', 13),
('Kab. Sekadau', 13),
('Kab. Sintang', 13),
('Kota Pontianak', 13),
('Kota Singkawang', 13),
('Kab. Balangan', 14),
('Kab. Banjar', 14),
('Kab. Barito Kuala', 14),
('Kab. Hulu Sungai Selatan', 14),
('Kab. Hulu Sungai Tengah', 14),
('Kab. Hulu Sungai Utara', 14),
('Kab. Kotabaru', 14),
('Kab. Tabalong', 14),
('Kab. Tanah Bumbu', 14),
('Kab. Tanah Laut', 14),
('Kab. Tapin', 14),
('Kota Banjarbaru', 14),
('Kota Banjarmasin', 14),
('Kab. Barito Selatan', 15),
('Kab. Barito Timur', 15),
('Kab. Barito Utara', 15),
('Kab. Gunung Mas', 15),
('Kab. Kapuas', 15),
('Kab. Katingan', 15),
('Kab. Kotawaringin Barat', 15),
('Kab. Kotawaringin Timur', 15),
('Kab. Lamandau', 15),
('Kab. Murung Raya', 15),
('Kab. Pulang Pisau', 15),
('Kab. Seruyan', 15),
('Kab. Sukamara', 15),
('Kota Palangka Raya', 15),
('Kab. Berau', 16),
('Kab. Kutai Barat', 16),
('Kab. Kutai Kartanegara', 16),
('Kab. Kutai Timur', 16),
('Kab. Mahakam Ulu', 16),
('Kab. Paser', 16),
('Kab. Penajam Paser Utara', 16),
('Kota Balikpapan', 16),
('Kota Bontang', 16),
('Kota Samarinda', 16),
('Kab. Bulungan', 17),
('Kab. Malinau', 17),
('Kab. Nunukan', 17),
('Kab. Tana Tidung', 17),
('Kota Tarakan', 17),
('Kab. Bintan', 18),
('Kab. Karimun', 18),
('Kab. Kepulauan Anambas', 18),
('Kab. Lingga', 18),
('Kab. Natuna', 18),
('Kota Batam', 18),
('Kota Tanjung Pinang', 18),
('Kab. Lampung Barat', 19),
('Kab. Lampung Selatan', 19),
('Kab. Lampung Tengah', 19),
('Kab. Lampung Timur', 19),
('Kab. Lampung Utara', 19),
('Kab. Mesuji', 19),
('Kab. Pesawaran', 19),
('Kab. Pesisir Barat', 19),
('Kab. Pringsewu', 19),
('Kab. Tanggamus', 19),
('Kab. Tulang Bawang', 19),
('Kab. Tulang Bawang Barat', 19),
('Kab. Way Kanan', 19),
('Kota Bandar Lampung', 19),
('Kota Metro', 19),
('Kab. Buru', 20),
('Kab. Buru Selatan', 20),
('Kab. Kepulauan Aru', 20),
('Kab. Maluku Barat Daya', 20),
('Kab. Maluku Tengah', 20),
('Kab. Maluku Tenggara', 20),
('Kab. Maluku Tenggara Barat', 20),
('Kab. Seram Bagian Barat', 20),
('Kab. Seram Bagian Timur', 20),
('Kota Ambon', 20),
('Kota Tual', 20),
('Kab. Halmahera Barat', 21),
('Kab. Halmahera Selatan', 21),
('Kab. Halmahera Tengah', 21),
('Kab. Halmahera Timur', 21),
('Kab. Halmahera Utara', 21),
('Kab. Kepulauan Sula', 21),
('Kab. Pulau Morotai', 21),
('Kab. Pulau Taliabu', 21),
('Kota Ternate', 21),
('Kota Tidore Kepulauan', 21),
('Kab. Bima', 22),
('Kab. Dompu', 22),
('Kab. Lombok Barat', 22),
('Kab. Lombok Tengah', 22),
('Kab. Lombok Timur', 22),
('Kab. Lombok Utara', 22),
('Kab. Sumbawa', 22),
('Kab. Sumbawa Barat', 22),
('Kota Bima', 22),
('Kota Mataram', 22),
('Kab. Alor', 23),
('Kab. Belu', 23),
('Kab. Ende', 23),
('Kab. Flores Timur', 23),
('Kab. Kupang', 23),
('Kab. Lembata', 23),
('Kab. Malaka', 23),
('Kab. Manggarai', 23),
('Kab. Manggarai Barat', 23),
('Kab. Manggarai Timur', 23),
('Kab. Nagekeo', 23),
('Kab. Ngada', 23),
('Kab. Rote Ndao', 23),
('Kab. Sabu Raijua', 23),
('Kab. Sikka', 23),
('Kab. Sumba Barat', 23),
('Kab. Sumba Barat Daya', 23),
('Kab. Sumba Tengah', 23),
('Kab. Sumba Timur', 23),
('Kab. Timor Tengah Selatan', 23),
('Kab. Timor Tengah Utara', 23),
('Kota Kupang', 23),
('Kab. Asmat', 24),
('Kab. Biak Numfor', 24),
('Kab. Boven Digoel', 24),
('Kab. Deiyai', 24),
('Kab. Dogiyai', 24),
('Kab. Intan Jaya', 24),
('Kab. Jayapura', 24),
('Kab. Jayawijaya', 24),
('Kab. Keerom', 24),
('Kab. Kepulauan Yapen', 24),
('Kab. Lanny Jaya', 24),
('Kab. Mamberamo Raya', 24),
('Kab. Mamberamo Tengah', 24),
('Kab. Mappi', 24),
('Kab. Merauke', 24),
('Kab. Mimika', 24),
('Kab. Nabire', 24),
('Kab. Nduga', 24),
('Kab. Paniai', 24),
('Kab. Pegunungan Bintang', 24),
('Kab. Puncak', 24),
('Kab. Puncak Jaya', 24),
('Kab. Sarmi', 24),
('Kab. Supiori', 24),
('Kab. Tolikara', 24),
('Kab. Waropen', 24),
('Kab. Yahukimo', 24),
('Kab. Yalimo', 24),
('Kota Jayapura', 24),
('Kab. Fakfak', 25),
('Kab. Kaimana', 25),
('Kab. Manokwari', 25),
('Kab. Manokwari Selatan', 25),
('Kab. Maybrat', 25),
('Kab. Pegunungan Arfak', 25),
('Kab. Raja Ampat', 25),
('Kab. Sorong', 25),
('Kab. Sorong Selatan', 25),
('Kab. Tambrauw', 25),
('Kab. Teluk Bintuni', 25),
('Kab. Teluk Wondama', 25),
('Kota Sorong', 25),
('Kab. Bengkalis', 26),
('Kab. Indragiri Hilir', 26),
('Kab. Indragiri Hulu', 26),
('Kab. Kampar', 26),
('Kab. Kepulauan Meranti', 26),
('Kab. Kuantan Singingi', 26),
('Kab. Pelalawan', 26),
('Kab. Rokan Hilir', 26),
('Kab. Rokan Hulu', 26),
('Kab. Siak', 26),
('Kota Dumai', 26),
('Kota Pekanbaru', 26),
('Kab. Majene', 27),
('Kab. Mamasa', 27),
('Kab. Mamuju', 27),
('Kab. Mamuju Tengah', 27),
('Kab. Mamuju Utara', 27),
('Kab. Polewali Mandar', 27),
('Kab. Bantaeng', 28),
('Kab. Barru', 28),
('Kab. Bone', 28),
('Kab. Bulukumba', 28),
('Kab. Enrekang', 28),
('Kab. Gowa', 28),
('Kab. Jeneponto', 28),
('Kab. Selayar', 28),
('Kab. Luwu', 28),
('Kab. Luwu Timur', 28),
('Kab. Luwu Utara', 28),
('Kab. Maros', 28),
('Kab. Pangkajene Kepulauan', 28),
('Kab. Pinrang', 28),
('Kab. Sidenreng Rappang', 28),
('Kab. Sinjai', 28),
('Kab. Soppeng', 28),
('Kab. Takalar', 28),
('Kab. Tana Toraja', 28),
('Kab. Toraja Utara', 28),
('Kab. Wajo', 28),
('Kota Makassar', 28),
('Kota Palopo', 28),
('Kota Parepare', 28),
('Kab. Banggai', 29),
('Kab. Banggai Kepulauan', 29),
('Kab. Banggai Laut', 29),
('Kab. Buol', 29),
('Kab. Donggala', 29),
('Kab. Morowali', 29),
('Kab. Morowali Utara', 29),
('Kab. Parigi Moutong', 29),
('Kab. Poso', 29),
('Kab. Sigi', 29),
('Kab. Tojo Una-Una', 29),
('Kab. Toli-Toli', 29),
('Kota Palu', 29),
('Kab. Bombana', 30),
('Kab. Buton', 30),
('Kab. Buton Selatan', 30),
('Kab. Buton Tengah', 30),
('Kab. Buton Utara', 30),
('Kab. Kolaka', 30),
('Kab. Kolaka Timur', 30),
('Kab. Kolaka Utara', 30),
('Kab. Konawe', 30),
('Kab. Konawe Kepulauan', 30),
('Kab. Konawe Selatan', 30),
('Kab. Konawe Utara', 30),
('Kab. Muna', 30),
('Kab. Muna Barat', 30),
('Kab. Wakatobi', 30),
('Kota Baubau', 30),
('Kota Kendari', 30),
('Kab. Bolaang Mongondow', 31),
('Kab. Bolaang Mongondow Selatan', 31),
('Kab. Bolaang Mongondow Timur', 31),
('Kab. Bolaang Mongondow Utara', 31),
('Kab. Kepulauan Sangihe', 31),
('Kab. Kepulauan Siau Tagulandang Biaro', 31),
('Kab. Kepulauan Talaud', 31),
('Kab. Minahasa', 31),
('Kab. Minahasa Selatan', 31),
('Kab. Minahasa Tenggara', 31),
('Kab. Minahasa Utara', 31),
('Kota Bitung', 31),
('Kota Kotamobagu', 31),
('Kota Manado', 31),
('Kota Tomohon', 31),
('Kab. Agam', 32),
('Kab. Dharmasraya', 32),
('Kab. Kepulauan Mentawai', 32),
('Kab. Lima Puluh Kota', 32),
('Kab. Padang Pariaman', 32),
('Kab. Pasaman', 32),
('Kab. Pasaman Barat', 32),
('Kab. Pesisir Selatan', 32),
('Kab. Sijunjung', 32),
('Kab. Solok', 32),
('Kab. Solok Selatan', 32),
('Kab. Tanah Datar', 32),
('Kota Bukittinggi', 32),
('Kota Padang', 32),
('Kota Padang Panjang', 32),
('Kota Pariaman', 32),
('Kota Payakumbuh', 32),
('Kota Sawahlunto', 32),
('Kota Solok', 32),
('Kab. Banyuasin', 33),
('Kab. Empat Lawang', 33),
('Kab. Lahat', 33),
('Kab. Muara Enim', 33),
('Kab. Musi Banyuasin', 33),
('Kab. Musi Rawas', 33),
('Kab. Musi Rawas Utara', 33),
('Kab. Ogan Ilir', 33),
('Kab. Ogan Komering Ilir', 33),
('Kab. Ogan Komering Ulu', 33),
('Kab. Ogan Komering Ulu Selatan', 33),
('Kab. Ogan Komering Ulu Timur', 33),
('Kab. Penukal Abab Lematang Ilir', 33),
('Kota Lubuk Linggau', 33),
('Kota Pagar Alam', 33),
('Kota Palembang', 33),
('Kota Prabumulih', 33),
('Kab. Asahan', 34),
('Kab. Batu Bara', 34),
('Kab. Dairi', 34),
('Kab. Deli Serdang', 34),
('Kab. Humbang Hasundutan', 34),
('Kab. Karo', 34),
('Kab. Labuhanbatu', 34),
('Kab. Labuhanbatu Selatan', 34),
('Kab. Labuhanbatu Utara', 34),
('Kab. Langkat', 34),
('Kab. Mandailing Natal', 34),
('Kab. Nias', 34),
('Kab. Nias Barat', 34),
('Kab. Nias Selatan', 34),
('Kab. Nias Utara', 34),
('Kab. Padang Lawas', 34),
('Kab. Padang Lawas Utara', 34),
('Kab. Pakpak Bharat', 34),
('Kab. Samosir', 34),
('Kab. Serdang Bedagai', 34),
('Kab. Simalungun', 34),
('Kab. Tapanuli Selatan', 34),
('Kab. Tapanuli Tengah', 34),
('Kab. Tapanuli Utara', 34),
('Kab. Toba Samosir', 34),
('Kota Binjai', 34),
('Kota Gunungsitoli', 34),
('Kota Medan', 34),
('Kota Padang Sidempuan', 34),
('Kota Pematangsiantar', 34),
('Kota Sibolga', 34),
('Kota Tanjung Balai', 34),
('Kota Tebing Tinggi', 34);