INSERT INTO `province` (`name`) VALUES
('Aceh'),
('Bali'),
('Kepulauan Bangka Belitung'),
('Banten'),
('Bengkulu'),
('Daerah Istimewa Yogyakarta'),
('Daerah Khusus Ibukota Jakarta'),
('Gorontalo'),
('Jambi'),
('Jawa Barat'),
('Jawa Tengah'),
('Jawa Timur'),
('Kalimantan Barat'),
('Kalimantan Selatan'),
('Kalimantan Tengah'),
('Kalimantan Timur'),
('Kalimantan Utara'),
('Kepulauan Riau'),
('Lampung'),
('Maluku'),
('Maluku Utara'),
('Nusa Tenggara Barat'),
('Nusa Tenggara Timur'),
('Papua'),
('Papua Barat'),
('Riau'),
('Sulawesi Barat'),
('Sulawesi Selatan'),
('Sulawesi Tengah'),
('Sulawesi Tenggara'),
('Sulawesi Utara'),
('Sumatra Barat'),
('Sumatra Selatan'),
('Sumatra Utara');